### ISSUE TITLE
merge_snps 

### ISSUE THREAD

**Issue by luoqingqing777** [czbiohub-sf/MIDAS2#108]
i have finished the `run_species` and `run_snps` steps. there is something wrong with `merge_snps`

I  used `midas2 merge_snps --samples_list list_of_samples.tsv --midasdb_name gtdb --midasdb_dir my_midasdb_Escherichia_coli --num_cores 10  --genome_coverage 0.0 --force   midas2_output/merge`

Here come:
Traceback (most recent call last):
File "/home/luoqingqing/.conda/envs/midas2.0/bin/midas2", line 8, in <module>
sys.exit(main())
File "/home/luoqingqing/.conda/envs/midas2.0/lib/python3.7/site-packages/midas2/__main__.py", line 24, in main
return subcommand_main(subcommand_args)
File "/home/luoqingqing/.conda/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 664, in main
merge_snps(args)
File "/home/luoqingqing/.conda/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 653, in merge_snps
raise error
File "/home/luoqingqing/.conda/envs/midas2.0/lib/python3.7/site-packages/midas2/subcommands/merge_snps.py", line 617, in merge_snps
assert species_ids_of_interest, f"No (specified) species pass the genome_coverage filter across samples, please adjust the genome_coverage or species_list"
AssertionError: No (specified) species pass the genome_coverage filter across samples, please adjust the genome_coverage or species_list

but i have adjusted the genome_coverage to 0, how can i make it more suitable to get the merge results.
waiting for your kind reply, many thanks

**Comment by zhaoc1** [comment]
Hi @luoqingqing777 ,

There are three metrics to select species for merge_snps: genome horizontal coverage, genome vertical coverage, and species prevalence. It seems like you also need to adjust the `--genome_depth` and `--sample_counts` by your `merge_snps` command, to compute the population SNPs for low abundant and low prevalent species.  Please refer to [ReadTheDoc](https://midas2.readthedocs.io/en/latest/snv_module.html#adjust-population-snv-filters) for more details. 

Thanks,
Chunyu
